### ISSUE TITLE
Proposal: Discord Group

### ISSUE THREAD

**Issue by qianxliu** [zoo-js/welcome#1]
I speak English because I think it is a great method for informative information. And I'm Chinese.

Come and adopt a cute you like, but it is not very clear to do what on next step.

It is a great idea, but what project we work on? Discord Group is a good place for classification and interaction. It's not a lot of Chinese using discord, but it is really appropriate for communication without stuff I think. Discord only need your email or not, and it could be accessed even without a client. 

Just like this: https://discord.gg/bRCvFy9

It is a real web client by websocket. Compared with QQ and WeChat, Discord is more powerful which means developer could use javascript to create Bot and Text Game, and it is free to access, even you have a email(client) or not. Discord could make smaller group from a huge group, and the threshold of English and GFW is also meaningful. Surely Discord actually could be accessed without proxy.

It is my proposal that I'm not sure that it is a really feasible idea to be adopted, but I think it is important for classification and interaction. Maybe there are more reasonable variants. I don't prefer to use telegram because it is politically inclined, and it actually couldn't be accessed without proxy. It is not funny.

Discord could also bind the notification of GitHub or other platform.

**Comment by qianxliu** [comment]
I hope others discuss with the proposal. Maybe it is my superfluous ideas. Actually I don't use GitHub very much recently.

**Comment by qianxliu** [comment]
希望有一个即时IM渠道（推荐Discord，实际上GitHub上使用Discord的人不少），而不是GitHub Discussion，因为响应速度过慢了。还有我不是JS技术栈的，虽然也略懂一些。关于具体建议和为什么推荐已经以英文形式写于上面了。And, maybe it is my superfluous ideas. 
@xrkffgg @ajuner

**Comment by xrkffgg** [comment]
实际上，可能大家来领养参与的都是抱有好玩尝试的目的。
之后更多的还是在忙自己的工作或者一些技术类开源。
这个项目以及相关的该怎样发展还没有想好。
我的想法是，自己挑选自己喜欢的名称，可以再里面做一些自己喜欢的项目什么的。

你的建议也很好。不过现在总领养人数大概60多，平时基本交流不太多。

**Comment by qianxliu** [comment]
其实我就是觉得zoo和分部之间关系几乎没有……如果用Discord的话可以分频道……而且比较方便……
Discord也可以用Javascript实现高级功能，绑定GitHub通知。

我是因为加org太麻烦了……好多次没人理我。有几次被人deal with

**Comment by qianxliu** [comment]
准确来说，就是没有归属感。

**Comment by xrkffgg** [comment]
一般比较大的项目，使用者和维护者都比较多的，会较容易形成社区，活跃度也高很多。

**Comment by xrkffgg** [comment]
现在 zoo 没什么主要的发展或者说目的，如果有好的建议，欢迎提出~
